//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_platformer : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.platformer_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.platformer_Jump;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotation
        {
            get
            {
                return SteamVR_Actions.platformer_Rotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotationRight
        {
            get
            {
                return SteamVR_Actions.platformer_RotationRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotationLeft
        {
            get
            {
                return SteamVR_Actions.platformer_RotationLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchPerspective
        {
            get
            {
                return SteamVR_Actions.platformer_SwitchPerspective;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.platformer_MenuButton;
            }
        }
    }
}
